version: "3.7"

services:
    jenkins-blueocean:
        image: yenght/myjenkins-blueocean:2.319.2-1
        mem_limit: 1g
        ports:
            - 8080:8080
            - 50000:50000
        environment:
            DOCKER_HOST: tcp://docker:2376
            DOCKER_CERT_PATH: /certs/client
            DOCKER_TLS_VERIFY: 1            
        volumes:
            - C:\ADOLFO\dev\lab\Docker\volumes\jenkins\jenkins-data:/var/jenkins_home
            - C:\ADOLFO\dev\lab\Docker\volumes\jenkins\jenkins-docker-certs:/certs/client:ro
    agent1:
        image: jenkins/ssh-agent:jdk11
        mem_limit: 256m
        ports:
            - 22:22
        environment:
            JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfo9cWc6zSJ/SrMqYvjyCSHQoozraSn8Tt4qbURTBszSdu45/ptyiXHrbw4ULbP4rDwqaH2Pc0VubuF4u1rxuSNdHi4T4Ig+QRnqVP32t2AWuKVk3bBAqE+MwAdDoOoqiAEVidM6sdEPIpij19Vul+zyS2YfMIXPCSp8sjL+tcooDngIV7dzK0+0gpJCCz30Z2AGYItOIvKl5GZsqG7ElG4FkGb+EIQIgdrjPsBX2ycUBE3b+unXkxs1L7jqKqxBMwCkaI48llkBnVZSUnUJ+wGtbtkzdRY3wxZKttd1tg+dfz1v4A2inEPvRl4NQRRHVaYRLbv80mBFEVT9zA2q8FzaIMIXi2/vX230C98bIJXg7q9CrqXmt61cG6SJemYIGemxv4PoYwdZK4bNdz8jlyJZ2Kv5Jy9kw8eE3sU5i16G/LITfd79kQBoK2DLTBp5e1a/G4c5z6g9fSlj3WZGUtmdQTN5GNY1TFZiYpxYP8u/E/u+Y2/9HiYyMwyro0A7c= jenkins@5a3451afaf3c
    agent2:
        image: jenkins/ssh-agent:jdk11
        mem_limit: 256m
        ports:
            - 23:22
        environment:
            JENKINS_AGENT_SSH_PUBKEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDfo9cWc6zSJ/SrMqYvjyCSHQoozraSn8Tt4qbURTBszSdu45/ptyiXHrbw4ULbP4rDwqaH2Pc0VubuF4u1rxuSNdHi4T4Ig+QRnqVP32t2AWuKVk3bBAqE+MwAdDoOoqiAEVidM6sdEPIpij19Vul+zyS2YfMIXPCSp8sjL+tcooDngIV7dzK0+0gpJCCz30Z2AGYItOIvKl5GZsqG7ElG4FkGb+EIQIgdrjPsBX2ycUBE3b+unXkxs1L7jqKqxBMwCkaI48llkBnVZSUnUJ+wGtbtkzdRY3wxZKttd1tg+dfz1v4A2inEPvRl4NQRRHVaYRLbv80mBFEVT9zA2q8FzaIMIXi2/vX230C98bIJXg7q9CrqXmt61cG6SJemYIGemxv4PoYwdZK4bNdz8jlyJZ2Kv5Jy9kw8eE3sU5i16G/LITfd79kQBoK2DLTBp5e1a/G4c5z6g9fSlj3WZGUtmdQTN5GNY1TFZiYpxYP8u/E/u+Y2/9HiYyMwyro0A7c= jenkins@5a3451afaf3c

